apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sovereign-ai-research-aiq
  namespace: openshift-gitops
  labels:
    gitops.ownedBy: cluster-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: sovereign-ai-research
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    repoURL: https://github.com/DevoteamNL/sovereign-ai-research.git
    targetRevision: rhdp-aws-downsize
    path: deploy/helm/aiq-rh
    helm:
      valueFiles:
        - values-vllm.yaml
      valuesObject:
        appname: sovereign-ai-research
        project:
          deploymentTarget: kind
        apps:
          backend:
            env:
              VLLM_BASE_URL: http://nemotron-nano-30b-predictor.sovereign-ai-research.svc.cluster.local:8080
              VLLM_ORCHESTRATOR_BASE_URL: http://gpt-oss-120b-predictor.sovereign-ai-research.svc.cluster.local:8080
              VLLM_SUMMARY_BASE_URL: http://nemotron-mini-4b-predictor.sovereign-ai-research.svc.cluster.local:8080
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 20m

# TODO change this so that it uses the smaller models specified to run on the smaller GPUs
# Add machine set for the 3rd GPU instance g5e
